package de.uniulm.iai.jqassistant.javasrc.plugin.model;

//import com.buschmais.xo.api.annotation.Abstract;
import com.buschmais.xo.neo4j.api.annotation.Label;

/**
 * Defines label "JavaSource" that gets applied to all nodes generated by this plugin.
 *
 * @author Steffen Kram
 */
//@Abstract
@Label("JavaSource")
public interface JavaSourceDescriptor {
}
